name: react-native-android-build-apk
on:
  push:
    branches:
      - master
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      
      - name: Install npm dependencies
        run: |
          cd test && npm install
          
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
        
      - name: Grant execute permission for gradlew
        run: cd test/android && chmod +x gradlew 
        
      - name: Build Android Release
        run: |
          cd test/android && ./gradlew app:assembleRelease
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
