name: react-native-android-build-apk
on:
  push:
    branches:
      - master
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      
      - name: Install npm dependencies
        run: |
          cd test && npm install
        
      - name: Build Android Release
        run: |
          ls -al
          cd test/android && chmod 777 ./gradlew
          cd test/android && ./gradlew assembleRelease
        working-directory: ${{ env.working-directory-root }}
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
